theme: jekyll-theme-minimal

# Author 配置博主信息
author: 'IPCreator'
nickname: 'AhaIPer'
bio: '专利'
avatar: 'https://user-images.githubusercontent.com/98626903/151642737-03db2c8d-bbde-42ee-9533-40579c33bff4.png'

# jekyll主题
title: IPCreator
description: "好专利，找爱知。"
logo: https://user-images.githubusercontent.com/98626903/151642737-03db2c8d-bbde-42ee-9533-40579c33bff4.png
author: 
  name: "IPCreator"

